= DG Cinema REST Docs 가이드
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
// :stylesdir: .asciidoctor/{css_dir_name}
// :stylesheet: style.css
:operation-curl-request-title: ######
:operation-httpie-request-title: ######
:operation-request-parameters-title: ######
:operation-path-parameters-title: ######
:operation-request-fields-title: ######
:operation-http-response-title: ######
:operation-response-body-title: ######
:operation-response-fields-title: ######

== 개요
'DG Cinema 프로젝트' REST Docs 문서입니다.

== 예매

=== 영화 조회
operation::movie-query-api-test/search-movie_return_value[snippets='curl-request,path-parameters']
operation::movie-query-api-test/search-movie_return_value[snippets='response-body,response-fields']

=== 영화 목록 조회
operation::movie-query-api-test/search-movie-list_return_value[snippets='curl-request']
operation::movie-query-api-test/search-movie-list_return_value[snippets='response-body,response-fields']

=== 상영관 조회
operation::theater-query-api-test/search-theater_return_value[snippets='curl-request,path-parameters']
operation::theater-query-api-test/search-theater_return_value[snippets='response-body,response-fields']

=== 상영관 목록 조회
operation::theater-query-api-test/search-theater-list_return_value[snippets='curl-request']
operation::theater-query-api-test/search-theater-list_return_value[snippets='response-body,response-fields']

=== 상영실 목록 조회
operation::theater-query-api-test/search-auditorium-list_return_value[snippets='curl-request,path-parameters']
operation::theater-query-api-test/search-auditorium-list_return_value[snippets='response-body,response-fields']
